const possibleGenresList = [
  "Science Fiction",
  "Fantasy",
  "Mystery",
  "Thriller",
  "Horror",
  "Romance",
  "Historical Fiction",
  "Biography",
  "Memoir",
  "Self-Help",
  "Cookbook",
  "Travel",
  "Poetry",
  "Dystopian",
  "Young Adult",
  "Graphic Novel",
  "Adventure",
  "Crime",
  "Humor",
  "Classic",
  "Philosophy",
  "Psychology",
  "Science",
  "Art",
  "Music",
  "Sports",
  "Business",
  "Economics",
  "Politics",
  "Religion",
  "Spirituality",
  "Science Fiction",
  "Fantasy",
  "Mystery",
  "Thriller",
  "Horror",
  "Romance",
  "Historical Fiction",
  "Biography",
  "Memoir",
  "Self-Help",
  "Cookbook",
  "Travel",
  "Poetry",
  "Dystopian",
  "Young Adult",
  "Graphic Novel",
  "Adventure",
  "Crime",
  "Humor",
  "Classic",
  "Philosophy",
  "Psychology",
  "Science",
  "Art",
  "Music",
  "Sports",
  "Business",
  "Economics",
  "Politics",
  "Religion",
  "Spirituality",
];

export const conditions = ["New", "Excellent", "Good", "Fair", "Poor"];

export const genresList = Array.from(new Set(possibleGenresList));
